import { Product } from './models/Product';

export const PRODUCTS: Product[] = [
  { Id: 1, Title:"Basic-TShirt", Image:"assets/images/Item_1.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:7.99, Comments: null },
  { Id: 2, Title:"Black Glasses", Image:"assets/images/Item_2.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:8.99, Comments: null },
  { Id: 3, Title:"Denim Shorts", Image:"assets/images/Item_3.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:12.99, Comments: null },
  { Id: 4, Title:"Fantasy Pants", Image:"assets/images/Item_4.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:13.99, Comments: null },
  { Id: 5, Title:"Fantasy TShirt", Image:"assets/images/Item_5.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:17.99, Comments: null },
  { Id: 6, Title:"Havana TShirt", Image:"assets/images/Item_6.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:14.99, Comments: null },
  { Id: 7, Title:"Shoes", Image:"assets/images/Item_7.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:37.99, Comments: null },
  { Id: 8, Title:"Shoulder Bag", Image:"assets/images/Item_8.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:23.99, Comments: null },
  { Id: 9, Title:"Simple Hat", Image:"assets/images/Item_9.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:2.99, Comments: null },
  { Id: 10, Title:"Striped Watch", Image:"assets/images/Item_10.jpg",Description:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes Lorem ipsum dolor sit amet.", Price:16.99, Comments: null }
];